import { Reward } from "./rewardTypes";
export const rewardData: Reward[] = [
  {
    id: 1,
    title: "Token listrik Rp. 20.000",
    description: "Token listrik untuk mendukung operasionalmu",
    poin: "500 EcoPoints",
    image: "/token.png",
    category: "digital",
  },
  {
    id: 2,
    title: "Token listrik Rp. 50.000",
    description: "Token listrik untuk mendukung operasionalmu",
    poin: "1200 EcoPoints",
    image: "/token.png",
    category: "digital",
  },
  {
    id: 3,
    title: "Voucher Gopay Rp. 10.000",
    description: "Voucher Gopay senilai 10.000",
    poin: "1000 EcoPoints",
    image: "/gopay.png",
    category: "digital",
  },
  {
    id: 4,
    title: "Voucher ShopeePay Rp.10.000",
    description: "Voucher ShopeePay senilai 10.000",
    poin: "+1000 EcoPoints",
    image: "/shopeepay.png",
    category: "digital",
  },
  {
    id: 5,
    title: "Paket data internet 5 GB",
    description: "catat observasi kondisi lahanmu hari ini",
    poin: "900 EcoPoints",
    image: "/laporanHarian.png",
    category: "digital",
  },
  {
    id: 6,
    title: "Voucher pulsa Rp. 20.000",
    description: "catat hasil perawatan lahanmu hari ini",
    poin: "900 EcoPoints",
    image: "/dataPerawatan.png",
    category: "digital",
  },
  {
    id: 7,
    title: "Pupuk Organik 10 Kg",
    description: "Pupuk organik berkualitas",
    poin: "1500 EcoPoints",
    image: "/pupuk.png",
    category: "pertanian",
  },
  {
    id: 8,
    title: "Bibit kelapa genjah",
    description: "Bibit kelapa genjah siap tanam 100 bibit",
    poin: "500 EcoPoints",
    image: "/bibit.png",
    category: "pertanian",
  },
];
